nelmio_api_doc:
    documentation:
        info:
            title: "API TÃ¢ches"
            description: "Documentation de l'API"
            version: "1.0.0"
    areas: # pour inclure toutes les routes
        default:
            path_patterns: [ '^/api' ]
