# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads/taches'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'

    # CORS Listener existant
    App\EventListener\CorsListener:
        tags:
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
